# Generated by Django 5.1.6 on 2025-03-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="stripe_session_id",
            field=models.CharField(
                blank=True, max_length=400, null=True, verbose_name="ID сессии Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payments",
            name="stripe_status",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Статус оплаты в Stripe",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "наличные"),
                    ("transfer", "перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                default="cash",
                max_length=10,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
