name: Test and Deploy DRF Project

on:
  push:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python manage.py test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 158.160.87.62 >> ~/.ssh/known_hosts

      - name: Copy project to server
        run: |
          rsync -rav --delete ./ test@158.160.87.62:~/drf-project

      - name: Deploy on server
        run: |
          ssh test@158.160.87.62 << 'EOF'
            cd ~/drf-project
            docker-compose down
            docker-compose up --build -d
            exit
          EOF

      - name: Cleanup SSH keys
        run: |
          rm -rf ~/.ssh